import type {
  CheckFinding,
  ConnectorError,
  GenerationEstimate,
  GenerationPreviewError,
  GenerationStatus,
  GenerationStop,
  GenerationUnit,
  StylePreset,
  Transcript,
  UnitCode,
  UnitWork,
  VideoRef,
} from "../../contract";
import { StylePresetSchema } from "../../contract";
import { planUnits, type Unit } from "../assembler";
import type { Checker } from "../checker";
import type { Connector } from "../connector";
import { FRAME_CONTRACT_VERSION } from "../frame";
import type { PreviewError, Previews } from "../preview";
import { createStatusStore, type Projects, type ProjectsError, type StoredVersion, type VideoContent } from "../projects";
import { StoryboardSchema, type Storyboard } from "../storyboard";
import { listPresets, presetBrief, storyboardRules, type PresetBrief } from "../style";
import type { Clock } from "../system";
import { writeStoryboard, writeUnitCode } from "./agents";

/** The model each agent role runs on until Settings choose others (Storyboard and Scene code: Opus). */
export const DEFAULT_MODELS = { storyboard: "claude-opus-5-5", sceneCode: "claude-opus-5-5" };

export type Models = typeof DEFAULT_MODELS;

/** Scene-code subagents running at once. */
const PARALLEL_UNITS = 4;

/** Spike numbers per minute of Voiceover with the default models (#7): 7-9 minutes of work, $3-5. */
const MINUTES_PER_MINUTE = { low: 7, high: 9 };
const COST_PER_MINUTE = { low: 3, high: 5 };

/** Why a unit a run didn't finish plays as its flagged fallback Scene, by what stopped the run. */
const STOP_REASONS = {
  stopped: "Generation was stopped before this Scene was finished.",
  "plan-limit": "The Claude plan's usage limit was reached before this Scene was finished.",
  authentication: "Claude's login failed before this Scene was finished.",
  closed: "The Project was closed before this Scene was finished.",
} satisfies Record<GenerationStop["cause"], string>;

export type GenerationOptions = {
  connector: Connector;
  checker: Checker;
  previews: Previews;
  projects: Projects;
  clock: Clock;
  /** Where agent sessions get their workspace folders. */
  workDir: string;
  models?: Models;
};

export type GenerateError =
  | Extract<ProjectsError, { code: "UNKNOWN_PROJECT" | "FILE_FAILED" }>
  | { code: "TRANSCRIPT_NOT_READY"; projectId: string }
  | { code: "GENERATING"; projectId: string }
  | { code: "ALREADY_GENERATED"; version: number }
  | { code: "UNKNOWN_STYLE_PRESET"; stylePreset: string }
  | { code: "NOT_GENERATED"; projectId: string }
  | { code: "NOT_FLAGGED"; units: string[] };

type Result<T, E> = { data: T; error: null } | { data: null; error: E };

export type Generation = ReturnType<typeof createGeneration>;

const IDLE: GenerationStatus = { state: "idle", units: [] };

type StatusStore = ReturnType<typeof createStatusStore<GenerationStatus>>;

/** A first generation or a Retry in progress: one per video at a time. */
type Run = {
  controller: AbortController;
  /** What stopped it, once something has. */
  stopped?: GenerationStop;
  /** Settles once the run has ended and saved what it keeps. */
  done: Promise<void>;
};

/**
 * Generation: a video's first generation, from the Project's Transcript to Version 1. The Storyboard
 * agent plans it; once the Storyboard is valid, parallel subagents write each unit's Scene code, the
 * Checker drives their retries, and a unit that keeps failing plays as its flagged fallback Scene.
 * Every finished unit is stored at once and the video plays as they finish. There is no approval
 * between the Storyboard and the Scenes, and nothing starts until Generate is pressed.
 *
 * Stop, a subscription plan limit, a failed login and closing the Project all end a run the same way:
 * finished units are kept and the rest become flagged fallbacks in a saved Version. Flagged units are
 * only ever regenerated by Retry.
 */
export function createGeneration({ connector, checker, previews, projects, clock, workDir, models = DEFAULT_MODELS }: GenerationOptions) {
  const videos = new Map<string, StatusStore>();
  const runs = new Map<string, Run>();

  // A closing Project stops its runs and waits for them to save, so their paid work outlives the window.
  projects.whenClosing(async (projectId) => {
    const closing = [...runs].filter(([key]) => key.startsWith(`${projectId} `)).map(([, run]) => run);
    closing.forEach((run) => halt(run, { cause: "closed" }));
    await Promise.all(closing.map(({ done }) => done));
  });

  function storeOf({ projectId, format }: VideoRef) {
    const key = `${projectId} ${format}`;
    const store = videos.get(key) ?? createStatusStore<GenerationStatus>(IDLE);
    videos.set(key, store);

    return { key, store };
  }

  /** Starts `work` as the video's run; a run that throws fails with the error. */
  function begin(key: string, store: StatusStore, work: (run: Run) => Promise<void>) {
    const run: Run = { controller: new AbortController(), done: Promise.resolve() };
    runs.set(key, run);
    run.done = work(run)
      .catch((cause: unknown) => store.update({ state: "failed", error: { code: "FILE_FAILED", path: workDir, message: String(cause) } }))
      .finally(() => {
        if (runs.get(key) === run) {
          runs.delete(key);
        }
      });
  }

  /** Ends a run early: the turns running now are interrupted, and nothing else starts. The first stop wins. */
  function halt(run: Run, stop: GenerationStop) {
    if (run.controller.signal.aborted) {
      return;
    }

    run.stopped = stop;
    run.controller.abort();
  }

  async function estimate({ projectId, format }: VideoRef): Promise<Result<GenerationEstimate, GenerateError>> {
    const { data: video, error } = await projects.video(projectId, format);

    if (error) {
      return { data: null, error: projectError(error) };
    }

    const minutes = video.project.voiceover.duration / 60;
    const low = Math.max(1, Math.round(minutes * MINUTES_PER_MINUTE.low));
    const span = { low, high: Math.max(low, Math.ceil(minutes * MINUTES_PER_MINUTE.high)) };

    if ((await connector.status()).method !== "api-key") {
      return { data: { minutes: span }, error: null };
    }

    return { data: { minutes: span, costUsd: { low: cents(minutes * COST_PER_MINUTE.low), high: cents(minutes * COST_PER_MINUTE.high) } }, error: null };
  }

  /** Starts generating the video; its progress streams through `watch`. */
  async function start(ref: VideoRef): Promise<Result<null, GenerateError>> {
    const { projectId, format } = ref;
    const { data: video, error } = await projects.video(projectId, format);

    if (error) {
      return { data: null, error: projectError(error) };
    }

    const { key, store } = storeOf(ref);

    if (runs.has(key)) {
      return { data: null, error: { code: "GENERATING", projectId } };
    }

    if (video.version !== undefined) {
      return { data: null, error: { code: "ALREADY_GENERATED", version: video.version } };
    }

    if (!video.transcript) {
      return { data: null, error: { code: "TRANSCRIPT_NOT_READY", projectId } };
    }

    const listed = listPresets().find(({ id }) => id === video.project.stylePreset);

    if (!listed) {
      return { data: null, error: { code: "UNKNOWN_STYLE_PRESET", stylePreset: video.project.stylePreset } };
    }

    store.set({ state: "planning", units: [] });
    const transcript = video.transcript;
    begin(key, store, (run) => generate({ run, ref, transcript, preset: StylePresetSchema.parse(listed), store }));

    return { data: null, error: null };
  }

  type GenerateRun = { run: Run; ref: VideoRef; transcript: Transcript; preset: StylePreset; store: StatusStore };

  async function generate({ run, ref, transcript, preset, store }: GenerateRun) {
    const { projectId, format } = ref;
    const captions = format === "vertical";
    const rules = storyboardRules(preset, { format, captions });
    const brief = presetBrief(preset, format);
    const { data: storyboard, error } = await writeStoryboard({
      connector,
      workDir,
      signal: run.controller.signal,
      model: models.storyboard,
      transcript,
      rules,
      brief,
    });

    if (error) {
      const stopped = run.stopped ?? (error.code === "AGENT_FAILED" ? stopOf(error.error) : undefined);

      // Before the Storyboard is valid there is nothing to keep: the Project stays as it was, ready to Generate again.
      store.set(stopped ? { state: "idle", units: [], stopped } : { state: "failed", units: [], error });
      return;
    }

    const units = planUnits(storyboard, transcript);
    const planned = units.map(({ id }) => id);
    const startedAt = new Date(clock.now()).toISOString();
    const content: VideoContent = { storyboard, preset, captions, units: {}, flags: [], models, frameContractVersion: FRAME_CONTRACT_VERSION };
    const saveRecord = () => projects.saveGeneration(projectId, format, { ...inUnitOrder(content, units), startedAt, planned });
    const progress = new Map<string, GenerationUnit>(units.map(({ id }) => [id, { id, status: "queued", attempts: 0 }]));
    const code: Record<string, UnitCode> = {};
    const publish = publisher({ ref, storyboard, transcript, rules, preset, code, progress, store });

    const { error: recordError } = await saveRecord();

    if (recordError) {
      return failed(publish, fileErrorOf(recordError));
    }

    await publish({ state: "writing" });
    const fileError = await writeUnits({ run, ref, storyboard, transcript, rules, preset, brief, units, content, code, publish, save: saveRecord });

    if (fileError) {
      return failed(publish, fileError);
    }

    const { data: version, error: versionError } = await projects.saveVersion(projectId, format, {
      ...inUnitOrder(content, units),
      origin: "generation",
      createdAt: new Date(clock.now()).toISOString(),
    });

    if (versionError) {
      return failed(publish, fileErrorOf(versionError));
    }

    await publish({ state: "done", version, stopped: run.stopped });
  }

  /**
   * Regenerates flagged fallback units of the video's newest Version with the Scene-code model, each by its own
   * subagent as in a first generation. Never runs on its own: only when the creator asks.
   */
  async function retry(ref: VideoRef, requested?: string[]): Promise<Result<null, GenerateError>> {
    const { projectId, format } = ref;
    const { data: video, error } = await projects.video(projectId, format);

    if (error) {
      return { data: null, error: projectError(error) };
    }

    const { key, store } = storeOf(ref);

    if (runs.has(key)) {
      return { data: null, error: { code: "GENERATING", projectId } };
    }

    if (!video.transcript) {
      return { data: null, error: { code: "TRANSCRIPT_NOT_READY", projectId } };
    }

    const { data: stored, error: readError } = await projects.latestVersion(projectId, format);

    if (readError) {
      return { data: null, error: projectError(readError) };
    }

    if (!stored) {
      return { data: null, error: { code: "NOT_GENERATED", projectId } };
    }

    const flagged = stored.version.flags.filter(({ kind }) => kind === "fallback").map(({ unit }) => unit);
    const wanted = [...new Set(requested ?? flagged)];
    const notFlagged = wanted.filter((unit) => !flagged.includes(unit));

    if (wanted.length === 0 || notFlagged.length > 0) {
      return { data: null, error: { code: "NOT_FLAGGED", units: notFlagged } };
    }

    const parsed = StoryboardSchema.safeParse(stored.version.storyboard);

    if (!parsed.success) {
      return { data: null, error: { code: "FILE_FAILED", path: `${format}/versions/${stored.version.version}.json`, message: parsed.error.message } };
    }

    // Checked again: another call may have started a run while this one read the Version.
    if (runs.has(key)) {
      return { data: null, error: { code: "GENERATING", projectId } };
    }

    const transcript = video.transcript;
    begin(key, store, (run) => retryUnits({ run, ref, transcript, stored, storyboard: parsed.data, wanted, store }));

    return { data: null, error: null };
  }

  type RetryRun = { run: Run; ref: VideoRef; transcript: Transcript; stored: StoredVersion; storyboard: Storyboard; wanted: string[]; store: StatusStore };

  async function retryUnits({ run, ref, transcript, stored, storyboard, wanted, store }: RetryRun) {
    const { projectId, format } = ref;
    const { version: current } = stored;
    const { preset, captions } = current;
    const rules = storyboardRules(preset, { format, captions });
    const brief = presetBrief(preset, format);
    const units = planUnits(storyboard, transcript);
    const targets = units.filter(({ id }) => wanted.includes(id));
    const code: Record<string, UnitCode> = { ...stored.code };
    const content: VideoContent = {
      storyboard,
      preset,
      captions,
      units: { ...current.units },
      flags: [...current.flags],
      models: { ...current.models, sceneCode: models.sceneCode },
      frameContractVersion: current.frameContractVersion,
    };
    const progress = new Map<string, GenerationUnit>(
      units.map(({ id }) => [id, { id, status: wanted.includes(id) ? "queued" : code[id] ? "ready" : "fallback", attempts: 0 }]),
    );
    const publish = publisher({ ref, storyboard, transcript, rules, preset, code, progress, store });

    await publish({ state: "writing", version: undefined, stopped: undefined, error: undefined });
    const fileError = await writeUnits({ run, ref, storyboard, transcript, rules, preset, brief, units: targets, content, code, publish });

    if (fileError) {
      return failed(publish, fileError);
    }

    // Only units that now pass change the video; otherwise it stays at its Version.
    if (!targets.some(({ id }) => code[id])) {
      return void (await publish({ state: "done", version: current.version, stopped: run.stopped }));
    }

    const { data: version, error: versionError } = await projects.saveVersion(projectId, format, {
      ...inUnitOrder(content, units),
      origin: "retry",
      createdAt: new Date(clock.now()).toISOString(),
    });

    if (versionError) {
      return failed(publish, fileErrorOf(versionError));
    }

    await publish({ state: "done", version, stopped: run.stopped });
  }

  type UnitsJob = {
    run: Run;
    ref: VideoRef;
    storyboard: Storyboard;
    transcript: Transcript;
    rules: ReturnType<typeof storyboardRules>;
    preset: StylePreset;
    brief: PresetBrief;
    units: Unit[];
    /** Updated as units finish: their hashes, and flags for those that play as fallbacks. */
    content: VideoContent;
    code: Record<string, UnitCode>;
    publish: Publish;
    /** Saves the run's progress after each unit. */
    save?: () => Promise<Result<null, ProjectsError>>;
  };

  /**
   * Writes the units' Scene code, 4 at a time, storing each as it passes. A plan limit or failed login stops the
   * run; once stopped, units still unfinished become flagged fallbacks without being asked of an agent.
   */
  async function writeUnits({ run, ref, storyboard, transcript, rules, preset, brief, units, content, code, publish, save }: UnitsJob) {
    const { signal } = run.controller;
    const baseline = signal.aborted ? [] : await pageFindings(storyboard, transcript, rules, preset);

    const results = await inParallel(units, PARALLEL_UNITS, async (unit): Promise<FileFailure | undefined> => {
      const outcome = signal.aborted
        ? { code: null, attempts: 0, reason: "" }
        : await writeUnitCode({
            connector,
            workDir,
            signal,
            model: models.sceneCode,
            checker,
            storyboard,
            transcript,
            rules,
            preset,
            brief,
            unit,
            baseline,
            onProgress: (status, attempts) => void publish({}, { id: unit.id, status, attempts }),
          });
      const others = content.flags.filter((flag) => flag.unit !== unit.id);

      if (outcome.code) {
        const { data: hash, error: unitError } = await projects.writeUnit(ref.projectId, ref.format, outcome.code);

        if (unitError) {
          return fileErrorOf(unitError);
        }

        code[unit.id] = outcome.code;
        content.units[unit.id] = hash;
        content.flags = others;
      } else {
        const stop = "error" in outcome && outcome.error ? stopOf(outcome.error) : undefined;

        if (stop) {
          halt(run, stop);
        }

        const reason = run.stopped ? STOP_REASONS[run.stopped.cause] : outcome.reason;
        content.flags = [...others, { unit: unit.id, kind: "fallback", reason }];
      }

      const saved = await save?.();
      await publish({}, { id: unit.id, status: outcome.code ? "ready" : "fallback", attempts: outcome.attempts });

      return saved?.error ? fileErrorOf(saved.error) : undefined;
    });

    return results.find((result) => result !== undefined);
  }

  /**
   * Publishes the video's status with a preview of it so far: units with code play it, the rest play
   * as the Storyboard animatic, or as fallback Scenes once they've failed. One at a time, in order.
   */
  function publisher({ ref, storyboard, transcript, rules, preset, code, progress, store }: PublishContext): Publish {
    let last = Promise.resolve();

    return (change: Partial<GenerationStatus>, unit?: GenerationUnit) => {
      if (unit) {
        progress.set(unit.id, unit);
      }

      last = last.then(async () => {
        const units = [...progress.values()];
        const pending = Object.fromEntries(units.filter(({ status }) => isWork(status)).map(({ id, status }) => [id, status as UnitWork]));
        const { data: video } = await projects.video(ref.projectId, ref.format);
        const source = { storyboard, transcript, rules, preset, code: { ...code }, pending, voiceover: video?.voiceoverPath };
        const { preview, previewError } = await previews.open(source).then(
          ({ data, error }) => ({ preview: data, previewError: error ? previewErrorOf(error) : undefined }),
          (cause: unknown) => ({ preview: null, previewError: thrown(cause) }),
        );

        store.set({ ...store.get(), ...change, units, preview: preview ?? store.get().preview, previewError });
      });

      return last;
    };
  }

  /** The Checker's findings on the page with every unit as its fallback Scene; none when it can't run, so every page-wide finding counts. */
  async function pageFindings(storyboard: Storyboard, transcript: Transcript, rules: ReturnType<typeof storyboardRules>, preset: StylePreset): Promise<CheckFinding[]> {
    const { data: report } = await checker.check({ storyboard, transcript, rules, preset, code: {} });

    return report?.findings ?? [];
  }

  /** Stops the video's run, if one is going, and resolves once it has saved what it keeps. */
  async function stop(ref: VideoRef): Promise<Result<null, GenerateError>> {
    const { error } = await projects.video(ref.projectId, ref.format);

    if (error) {
      return { data: null, error: projectError(error) };
    }

    const run = runs.get(storeOf(ref).key);

    if (run) {
      halt(run, { cause: "stopped" });
      await run.done;
    }

    return { data: null, error: null };
  }

  /** Streams the generation of a video of an open Project: `idle` until Generate is pressed. */
  async function watch(ref: VideoRef, signal?: AbortSignal): Promise<Result<AsyncGenerator<GenerationStatus>, GenerateError>> {
    const { error } = await projects.video(ref.projectId, ref.format);

    if (error) {
      return { data: null, error: projectError(error) };
    }

    return { data: storeOf(ref).store.watch(signal), error: null };
  }

  return { estimate, start, stop, retry, watch };
}

type Publish = (change: Partial<GenerationStatus>, unit?: GenerationUnit) => Promise<void>;

type PublishContext = {
  ref: VideoRef;
  storyboard: Storyboard;
  transcript: Transcript;
  rules: ReturnType<typeof storyboardRules>;
  preset: StylePreset;
  code: Record<string, UnitCode>;
  progress: Map<string, GenerationUnit>;
  store: StatusStore;
};

type FileFailure = { path: string; message: string };

/** The connector errors that end the whole run as Stop does, rather than fail one unit. */
function stopOf(error: ConnectorError): GenerationStop | undefined {
  if (error.code === "PLAN_LIMIT") {
    return { cause: "plan-limit", resetsAt: error.resetsAt };
  }

  if (error.code === "AUTHENTICATION_FAILED") {
    return { cause: "authentication" };
  }

  return undefined;
}

function failed(publish: Publish, { path, message }: FileFailure) {
  return publish({ state: "failed", error: { code: "FILE_FAILED", path, message } });
}

function isWork(status: GenerationUnit["status"]): boolean {
  return status === "queued" || status === "writing" || status === "checking";
}

/** Units finish in any order; the files list them in the Storyboard's, so the same video always saves the same. */
function inUnitOrder(content: VideoContent, units: Unit[]): VideoContent {
  const order = (id: string) => units.findIndex((unit) => unit.id === id);
  const hashes = units.flatMap(({ id }) => (content.units[id] ? [[id, content.units[id]] as const] : []));

  return { ...content, units: Object.fromEntries(hashes), flags: [...content.flags].sort((a, b) => order(a.unit) - order(b.unit)) };
}

function fileErrorOf(error: ProjectsError): FileFailure {
  if (error.code === "FILE_FAILED") {
    return { path: error.path, message: error.message };
  }

  return { path: "", message: error.code };
}

function projectError(error: ProjectsError): GenerateError {
  if (error.code === "UNKNOWN_PROJECT" || error.code === "FILE_FAILED") {
    return error;
  }

  return { code: "FILE_FAILED", path: "", message: error.code };
}

function thrown(cause: unknown): GenerationPreviewError {
  return { code: "PREVIEW_FAILED", message: cause instanceof Error ? cause.message : String(cause) };
}

function previewErrorOf(error: PreviewError): GenerationPreviewError {
  switch (error.code) {
    case "VOICEOVER_MISSING":
      return { code: error.code, message: `The Voiceover isn't at ${error.path} any more.` };
    case "INVALID_STORYBOARD":
      return { code: error.code, message: error.issues.map((issue) => issue.message).join(" ") };
    case "UNKNOWN_UNIT":
      return { code: error.code, message: `The Storyboard has no unit ${error.unit}.` };
  }
}

function cents(dollars: number): number {
  return Math.round(dollars * 100) / 100;
}

/** Runs `work` on every item, at most `limit` at once, and resolves with the results in order. */
async function inParallel<T, R>(items: T[], limit: number, work: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = [];
  let next = 0;
  const worker = async () => {
    while (next < items.length) {
      const index = next++;
      results[index] = await work(items[index] as T);
    }
  };

  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));

  return results;
}
